### ISSUE TITLE
Portal mismatch to dashboard, shouldn't it redirect to dashboard?

### ISSUE THREAD

**Issue by Parkers145** [threefoldtecharchive/tfgrid_dashboard#430] opened 2022-12-05 16:54 UTC
Farmer Micheal was reporting that he could not see half of his nodes in the portal. It is my understanding that the portal should not be used anymore and should redirect to dashboard, this is the exact link he used and i was able to reproduce his problem. 

       portal.grid.tf

![image](https://user-images.githubusercontent.com/44621168/205694893-cf1dcc94-74de-4ed3-abf2-49bc88b6d812.png)

When I mentioned using dashboard to him he also brought up that rounding on dashboard was different from port and that he was using it because dashboards measurement didn't change when he added a 512gb ssd,  so he was using portal to verify that his upgrade was detected. this sounds like possible a rounding setting? 

![image](https://user-images.githubusercontent.com/44621168/205695020-a61f95d7-9704-4cd5-b9e2-fc7fb4a6d5b3.png)

Lastly once on dashboard, you can click the next page when showing 50 nodes, 

![image](https://user-images.githubusercontent.com/44621168/205695560-87145246-a3bd-4ad5-8075-7e6e0a01789b.png)

**Comment by xmonader** [comment] 2022-12-12 10:10
@coesensbert isn't it the case already?

**Comment by coesensbert** [comment] 2022-12-12 13:49
The old portal is not running anywhere anymore, so there is probably some confusion going on. Not sure how to explain the behavior above but these 4 url's point to the same exact dashboard pod/service.
- portal.grid.tf
- explorer.grid.tf
- explorer3.grid.tf
- explorer.threefold.io

So the above urls point to the same dashboard service as dashboard.grid.tf

I will change the ingresses by actual http redirects to dashboard.grid.tf: https://github.com/threefoldtech/tf_operations/issues/1303

**Comment by Parkers145** [comment] 2022-12-12 19:40
Michael Added some information to his struggles with verifying his capacity in chat, 

He reported that the reason he was using explorer to check his nodes SRU capacity is because when he attempts to veiw his nodes in his farm on HTTPS:\\Dashboard.grid.tf by going to Portal->Farm->Your Farm Nodes and selects the "all" option he is only able to view the first 50 nodes in his farm that has 100+ nodes. regardless of what display size range he chooses, it only displays 50 nodes. 

here is the chat 
![image](https://user-images.githubusercontent.com/44621168/207138155-835d7a12-cf3f-4080-bb40-6c89fa09e80f.png)

![image](https://user-images.githubusercontent.com/44621168/207138229-e0dd54d1-0f34-484c-bfa0-8846e4f7b89f.png)
 
this is the box that he reports will only display 50 nodes regardless of size choice.

**Comment by coesensbert** [comment] 2022-12-13 09:36
Best make another ticket out of this? Since it's now about listing nodes.
Can't reproduce the issue, since we don't have more then 50 nodes in our freefarm. But selecting 5, 10 or 15 seems to work here.

**Comment by Parkers145** [comment] 2022-12-13 09:39
Yea we can probably close this one and open a better titled ticket, I'm not sure who other then Michael does have more then 50 nodes though.

**Comment by AhmedHanafy725** [comment] 2022-12-15 11:01
this issue is resolved here #387, but it's not released on mainnet yet

**Comment by A-Harby** [comment] 2022-12-20 11:21
> ```
>    portal.grid.tf
> ```

Now directs to the [dashboard](https://dashboard.grid.tf/) , same to all the different networks fixed in the [issue](https://github.com/threefoldtech/tf_operations/issues/1303)

**Closed as completed by A-Harby** 2022-12-20 11:21 UTC
